import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import { Icons } from "@/components/icons";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          footerActionLink: {
            backgroundColor: "white",
            color: "#86BA94",
          },
          formButtonPrimary:
            "bg-[#86BA94] hover:bg-[#86BA94] text-sm normal-case",
          card: "shadow-lg ",
          headerTitle: "text-[#86BA94]",
          headerSubtitle: "text-[#263238] font-bold",
          dividerText: "text-[#86BA94]",
        },
        variables: {
          colorText: "black",
        },
      }}
    >
      <html lang="en">
        <body>
          <ClerkLoading>
            <div className="flex w-full h-[100vh] align-middle mt-[200px] justify-center">
              <Icons.avatar className=""/>
            </div>
          </ClerkLoading>
          <ClerkLoaded>{children}</ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
